import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../core/theme/jumns_colors.dart';
import '../../../core/theme/charcoal_decorations.dart';
import '../../../core/models/agent_card.dart';

/// Renders proactive insight cards in the chat stream.
/// These are generated by the backend's proactive engine (proactive-engine.ts)
/// which detects at-risk goals, task overload, stale goals, and generates
/// AI-powered suggestions — borrowing from OpenClaw's auto-reply pattern.
class InsightCardWidget extends StatelessWidget {
  final InsightCard card;
  const InsightCardWidget({super.key, required this.card});

  @override
  Widget build(BuildContext context) {
    final color = card.priority == 'high'
        ? JumnsColors.coral
        : card.priority == 'medium'
            ? JumnsColors.amber
            : JumnsColors.mint;

    return Container(
      margin: const EdgeInsets.symmetric(vertical: 6),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color.withAlpha(30),
        borderRadius: kCharcoalRadiusAlt,
        border: Border.all(color: JumnsColors.ink, width: 2),
        boxShadow: const [
          BoxShadow(color: JumnsColors.borderShadow, offset: Offset(2, 2)),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text('💡', style: const TextStyle(fontSize: 18)),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  card.title,
                  style: GoogleFonts.gloriaHallelujah(
                    fontSize: 15,
                    fontWeight: FontWeight.bold,
                    color: JumnsColors.charcoal,
                  ),
                ),
              ),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: color.withAlpha(80),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  card.priority,
                  style: GoogleFonts.architectsDaughter(
                    fontSize: 10,
                    fontWeight: FontWeight.w700,
                    color: JumnsColors.charcoal,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            card.content,
            style: GoogleFonts.architectsDaughter(
              fontSize: 14,
              fontWeight: FontWeight.w700,
              color: JumnsColors.ink,
              height: 1.4,
            ),
          ),
          if (card.suggestedAction != null) ...[
            const SizedBox(height: 10),
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: JumnsColors.surface,
                borderRadius: kCharcoalRadius,
                border: Border.all(
                    color: JumnsColors.ink.withAlpha(100), width: 1),
              ),
              child: Row(
                children: [
                  Icon(Icons.lightbulb_outline,
                      size: 16, color: JumnsColors.amber),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      card.suggestedAction!,
                      style: GoogleFonts.architectsDaughter(
                        fontSize: 13,
                        fontWeight: FontWeight.w700,
                        color: JumnsColors.charcoal,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}
